### ISSUE TITLE
 could you change the release name of rplidar_ros in indigo version of your cob_substitute.

### ISSUE THREAD

**Issue by kintzhao** [ipa320/cob_substitute#36]
I am a member of rplidar, when I plan to release indigo version of rplidar_ros ,  meetting the erro notice:

There's a package released with that name already: https://github.com/ros/rosdistro/blob/master/indigo/distribution.yaml#L1428 You should coordinate with the maintainers of cob_substitution about the package naming. Probably through a ticket here: https://github.com/ipa320/cob_substitute/issues

**Comment by floweisshardt** [comment]
I'll do a rerelease of cob_substitute without rplidar.

**Comment by mgruhler** [comment]
great! Thanks @ipa-fmw

**Comment by floweisshardt** [comment]
rereleased, see https://github.com/ros/rosdistro/pull/11289
